#############################################################################
# Makefile for building: Qt_test
# Generated by qmake (2.01a) (Qt 4.8.3) on: Sa. Mai 4 18:11:37 2013
# Project:  Qt_test.pro
# Template: app
# Command: /home/msw/crossdev/OSELAS.BSP-RaspberryPi/platform-RaspberryPi/sysroot-cross/bin/qmake-cross -spec /opt/qt-4.8.3e-armhf/sysroot-target/usr/mkspecs/qws/linux-ptx-g++ -o Makefile Qt_test.pro
#############################################################################

####### Compiler, tools and options

CC            = arm-1136jfs-linux-gnueabihf-gcc
CXX           = arm-1136jfs-linux-gnueabihf-g++
DEFINES       = -DQT_NO_DEBUG -DQT_GUI_LIB -DQT_NETWORK_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -pipe -isystem /home/msw/crossdev/OSELAS.BSP-RaspberryPi/platform-RaspberryPi/sysroot-target/include -isystem /home/msw/crossdev/OSELAS.BSP-RaspberryPi/platform-RaspberryPi/sysroot-target/usr/include -O2 -Wall -W -D_REENTRANT $(DEFINES)
CXXFLAGS      = -pipe -isystem /home/msw/crossdev/OSELAS.BSP-RaspberryPi/platform-RaspberryPi/sysroot-target/include -isystem /home/msw/crossdev/OSELAS.BSP-RaspberryPi/platform-RaspberryPi/sysroot-target/usr/include -O2 -Wall -W -D_REENTRANT $(DEFINES)
INCPATH       = -I/opt/qt-4.8.3e-armhf/sysroot-target/usr/mkspecs/qws/linux-ptx-g++ -I. -I/opt/qt-4.8.3e-armhf/sysroot-target/usr/include/QtCore -I/opt/qt-4.8.3e-armhf/sysroot-target/usr/include/QtNetwork -I/opt/qt-4.8.3e-armhf/sysroot-target/usr/include/QtGui -I/opt/qt-4.8.3e-armhf/sysroot-target/usr/include -I. -I. -I/opt/qt-4.8.3e-armhf/sysroot-target/include -I/opt/qt-4.8.3e-armhf/sysroot-target/usr/include
LINK          = arm-1136jfs-linux-gnueabihf-g++
LFLAGS        = -L/home/msw/crossdev/OSELAS.BSP-RaspberryPi/platform-RaspberryPi/sysroot-target/lib -L/home/msw/crossdev/OSELAS.BSP-RaspberryPi/platform-RaspberryPi/sysroot-target/usr/lib -Wl,-rpath-link -Wl,/home/msw/crossdev/OSELAS.BSP-RaspberryPi/platform-RaspberryPi/sysroot-target/lib -Wl,-rpath-link -Wl,/home/msw/crossdev/OSELAS.BSP-RaspberryPi/platform-RaspberryPi/sysroot-target/usr/lib -Wl,-O1
LIBS          = $(SUBLIBS)  -L/home/msw/crossdev/OSELAS.BSP-RaspberryPi/platform-RaspberryPi/sysroot-target/lib -L/home/msw/crossdev/OSELAS.BSP-RaspberryPi/platform-RaspberryPi/sysroot-target/usr/lib -lQtGui -L/home/msw/crossdev/OSELAS.BSP-RaspberryPi/platform-RaspberryPi/sysroot-target/usr/lib -L/home/msw/crossdev/OSELAS.BSP-RaspberryPi/platform-RaspberryPi/sysroot-target/lib -lQtNetwork -lQtCore -lpthread 
AR            = arm-1136jfs-linux-gnueabihf-ar cqs
RANLIB        = 
QMAKE         = /home/msw/crossdev/OSELAS.BSP-RaspberryPi/platform-RaspberryPi/sysroot-cross/bin/qmake-cross
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
STRIP         = arm-1136jfs-linux-gnueabihf-strip
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.cpp \
		mainwindow.cpp \
		qcustomplot.cpp moc_mainwindow.cpp \
		moc_qcustomplot.cpp
OBJECTS       = main.o \
		mainwindow.o \
		qcustomplot.o \
		moc_mainwindow.o \
		moc_qcustomplot.o
DIST          = /opt/qt-4.8.3e-armhf/sysroot-target/usr/mkspecs/common/gcc-base.conf \
		/opt/qt-4.8.3e-armhf/sysroot-target/usr/mkspecs/common/gcc-base-unix.conf \
		/opt/qt-4.8.3e-armhf/sysroot-target/usr/mkspecs/common/g++-base.conf \
		/opt/qt-4.8.3e-armhf/sysroot-target/usr/mkspecs/common/g++-unix.conf \
		/opt/qt-4.8.3e-armhf/sysroot-target/usr/mkspecs/common/unix.conf \
		/opt/qt-4.8.3e-armhf/sysroot-target/usr/mkspecs/common/linux.conf \
		/opt/qt-4.8.3e-armhf/sysroot-target/usr/mkspecs/common/qws.conf \
		/opt/qt-4.8.3e-armhf/sysroot-target/usr/mkspecs/qconfig.pri \
		/opt/qt-4.8.3e-armhf/sysroot-target/usr/mkspecs/modules/qt_webkit_version.pri \
		/opt/qt-4.8.3e-armhf/sysroot-target/usr/mkspecs/features/qt_functions.prf \
		/opt/qt-4.8.3e-armhf/sysroot-target/usr/mkspecs/features/qt_config.prf \
		/opt/qt-4.8.3e-armhf/sysroot-target/usr/mkspecs/features/exclusive_builds.prf \
		/opt/qt-4.8.3e-armhf/sysroot-target/usr/mkspecs/features/default_pre.prf \
		/opt/qt-4.8.3e-armhf/sysroot-target/usr/mkspecs/features/release.prf \
		/opt/qt-4.8.3e-armhf/sysroot-target/usr/mkspecs/features/default_post.prf \
		/opt/qt-4.8.3e-armhf/sysroot-target/usr/mkspecs/features/warn_on.prf \
		/opt/qt-4.8.3e-armhf/sysroot-target/usr/mkspecs/features/qt.prf \
		/opt/qt-4.8.3e-armhf/sysroot-target/usr/mkspecs/features/unix/thread.prf \
		/opt/qt-4.8.3e-armhf/sysroot-target/usr/mkspecs/features/moc.prf \
		/opt/qt-4.8.3e-armhf/sysroot-target/usr/mkspecs/features/resources.prf \
		/opt/qt-4.8.3e-armhf/sysroot-target/usr/mkspecs/features/uic.prf \
		/opt/qt-4.8.3e-armhf/sysroot-target/usr/mkspecs/features/yacc.prf \
		/opt/qt-4.8.3e-armhf/sysroot-target/usr/mkspecs/features/lex.prf \
		/opt/qt-4.8.3e-armhf/sysroot-target/usr/mkspecs/features/include_source_dir.prf \
		Qt_test.pro
QMAKE_TARGET  = Qt_test
DESTDIR       = 
TARGET        = Qt_test

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(INCPATH) $(CXXFLAGS) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(INCPATH) $(CXXFLAGS) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(INCPATH) $(CXXFLAGS) -o "$@" "$<"

.C.o:
	$(CXX) -c $(INCPATH) $(CXXFLAGS) -o "$@" "$<"

.c.o:
	$(CC) -c $(INCPATH) $(CFLAGS) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET): ui_mainwindow.h $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: Qt_test.pro  /opt/qt-4.8.3e-armhf/sysroot-target/usr/mkspecs/qws/linux-ptx-g++/qmake.conf /opt/qt-4.8.3e-armhf/sysroot-target/usr/mkspecs/common/gcc-base.conf \
		/opt/qt-4.8.3e-armhf/sysroot-target/usr/mkspecs/common/gcc-base-unix.conf \
		/opt/qt-4.8.3e-armhf/sysroot-target/usr/mkspecs/common/g++-base.conf \
		/opt/qt-4.8.3e-armhf/sysroot-target/usr/mkspecs/common/g++-unix.conf \
		/opt/qt-4.8.3e-armhf/sysroot-target/usr/mkspecs/common/unix.conf \
		/opt/qt-4.8.3e-armhf/sysroot-target/usr/mkspecs/common/linux.conf \
		/opt/qt-4.8.3e-armhf/sysroot-target/usr/mkspecs/common/qws.conf \
		/opt/qt-4.8.3e-armhf/sysroot-target/usr/mkspecs/qconfig.pri \
		/opt/qt-4.8.3e-armhf/sysroot-target/usr/mkspecs/modules/qt_webkit_version.pri \
		/opt/qt-4.8.3e-armhf/sysroot-target/usr/mkspecs/features/qt_functions.prf \
		/opt/qt-4.8.3e-armhf/sysroot-target/usr/mkspecs/features/qt_config.prf \
		/opt/qt-4.8.3e-armhf/sysroot-target/usr/mkspecs/features/exclusive_builds.prf \
		/opt/qt-4.8.3e-armhf/sysroot-target/usr/mkspecs/features/default_pre.prf \
		/opt/qt-4.8.3e-armhf/sysroot-target/usr/mkspecs/features/release.prf \
		/opt/qt-4.8.3e-armhf/sysroot-target/usr/mkspecs/features/default_post.prf \
		/opt/qt-4.8.3e-armhf/sysroot-target/usr/mkspecs/features/warn_on.prf \
		/opt/qt-4.8.3e-armhf/sysroot-target/usr/mkspecs/features/qt.prf \
		/opt/qt-4.8.3e-armhf/sysroot-target/usr/mkspecs/features/unix/thread.prf \
		/opt/qt-4.8.3e-armhf/sysroot-target/usr/mkspecs/features/moc.prf \
		/opt/qt-4.8.3e-armhf/sysroot-target/usr/mkspecs/features/resources.prf \
		/opt/qt-4.8.3e-armhf/sysroot-target/usr/mkspecs/features/uic.prf \
		/opt/qt-4.8.3e-armhf/sysroot-target/usr/mkspecs/features/yacc.prf \
		/opt/qt-4.8.3e-armhf/sysroot-target/usr/mkspecs/features/lex.prf \
		/opt/qt-4.8.3e-armhf/sysroot-target/usr/mkspecs/features/include_source_dir.prf \
		/home/msw/crossdev/OSELAS.BSP-RaspberryPi/platform-RaspberryPi/sysroot-target/usr/lib/libQtGui.prl \
		/home/msw/crossdev/OSELAS.BSP-RaspberryPi/platform-RaspberryPi/sysroot-target/usr/lib/libQtNetwork.prl \
		/home/msw/crossdev/OSELAS.BSP-RaspberryPi/platform-RaspberryPi/sysroot-target/usr/lib/libQtCore.prl
	$(QMAKE) -spec /opt/qt-4.8.3e-armhf/sysroot-target/usr/mkspecs/qws/linux-ptx-g++ -o Makefile Qt_test.pro
/opt/qt-4.8.3e-armhf/sysroot-target/usr/mkspecs/common/gcc-base.conf:
/opt/qt-4.8.3e-armhf/sysroot-target/usr/mkspecs/common/gcc-base-unix.conf:
/opt/qt-4.8.3e-armhf/sysroot-target/usr/mkspecs/common/g++-base.conf:
/opt/qt-4.8.3e-armhf/sysroot-target/usr/mkspecs/common/g++-unix.conf:
/opt/qt-4.8.3e-armhf/sysroot-target/usr/mkspecs/common/unix.conf:
/opt/qt-4.8.3e-armhf/sysroot-target/usr/mkspecs/common/linux.conf:
/opt/qt-4.8.3e-armhf/sysroot-target/usr/mkspecs/common/qws.conf:
/opt/qt-4.8.3e-armhf/sysroot-target/usr/mkspecs/qconfig.pri:
/opt/qt-4.8.3e-armhf/sysroot-target/usr/mkspecs/modules/qt_webkit_version.pri:
/opt/qt-4.8.3e-armhf/sysroot-target/usr/mkspecs/features/qt_functions.prf:
/opt/qt-4.8.3e-armhf/sysroot-target/usr/mkspecs/features/qt_config.prf:
/opt/qt-4.8.3e-armhf/sysroot-target/usr/mkspecs/features/exclusive_builds.prf:
/opt/qt-4.8.3e-armhf/sysroot-target/usr/mkspecs/features/default_pre.prf:
/opt/qt-4.8.3e-armhf/sysroot-target/usr/mkspecs/features/release.prf:
/opt/qt-4.8.3e-armhf/sysroot-target/usr/mkspecs/features/default_post.prf:
/opt/qt-4.8.3e-armhf/sysroot-target/usr/mkspecs/features/warn_on.prf:
/opt/qt-4.8.3e-armhf/sysroot-target/usr/mkspecs/features/qt.prf:
/opt/qt-4.8.3e-armhf/sysroot-target/usr/mkspecs/features/unix/thread.prf:
/opt/qt-4.8.3e-armhf/sysroot-target/usr/mkspecs/features/moc.prf:
/opt/qt-4.8.3e-armhf/sysroot-target/usr/mkspecs/features/resources.prf:
/opt/qt-4.8.3e-armhf/sysroot-target/usr/mkspecs/features/uic.prf:
/opt/qt-4.8.3e-armhf/sysroot-target/usr/mkspecs/features/yacc.prf:
/opt/qt-4.8.3e-armhf/sysroot-target/usr/mkspecs/features/lex.prf:
/opt/qt-4.8.3e-armhf/sysroot-target/usr/mkspecs/features/include_source_dir.prf:
/home/msw/crossdev/OSELAS.BSP-RaspberryPi/platform-RaspberryPi/sysroot-target/usr/lib/libQtGui.prl:
/home/msw/crossdev/OSELAS.BSP-RaspberryPi/platform-RaspberryPi/sysroot-target/usr/lib/libQtNetwork.prl:
/home/msw/crossdev/OSELAS.BSP-RaspberryPi/platform-RaspberryPi/sysroot-target/usr/lib/libQtCore.prl:
qmake:  FORCE
	@$(QMAKE) -spec /opt/qt-4.8.3e-armhf/sysroot-target/usr/mkspecs/qws/linux-ptx-g++ -o Makefile Qt_test.pro

dist: 
	@$(CHK_DIR_EXISTS) .tmp/Qt_test1.0.0 || $(MKDIR) .tmp/Qt_test1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/Qt_test1.0.0/ && $(COPY_FILE) --parents mainwindow.h qcustomplot.h .tmp/Qt_test1.0.0/ && $(COPY_FILE) --parents main.cpp mainwindow.cpp qcustomplot.cpp .tmp/Qt_test1.0.0/ && $(COPY_FILE) --parents mainwindow.ui .tmp/Qt_test1.0.0/ && (cd `dirname .tmp/Qt_test1.0.0` && $(TAR) Qt_test1.0.0.tar Qt_test1.0.0 && $(COMPRESS) Qt_test1.0.0.tar) && $(MOVE) `dirname .tmp/Qt_test1.0.0`/Qt_test1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/Qt_test1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


check: first

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all: moc_mainwindow.cpp moc_qcustomplot.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_mainwindow.cpp moc_qcustomplot.cpp
moc_mainwindow.cpp: qcustomplot.h \
		mainwindow.h
	/home/msw/crossdev/OSELAS.BSP-RaspberryPi/platform-RaspberryPi/sysroot-host/bin/moc $(DEFINES) $(INCPATH) mainwindow.h -o moc_mainwindow.cpp

moc_qcustomplot.cpp: qcustomplot.h
	/home/msw/crossdev/OSELAS.BSP-RaspberryPi/platform-RaspberryPi/sysroot-host/bin/moc $(DEFINES) $(INCPATH) qcustomplot.h -o moc_qcustomplot.cpp

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: ui_mainwindow.h
compiler_uic_clean:
	-$(DEL_FILE) ui_mainwindow.h
ui_mainwindow.h: mainwindow.ui \
		qcustomplot.h
	/home/msw/crossdev/OSELAS.BSP-RaspberryPi/platform-RaspberryPi/sysroot-host/bin/uic mainwindow.ui -o ui_mainwindow.h

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean compiler_uic_clean 

####### Compile

main.o: main.cpp mainwindow.h \
		qcustomplot.h
	$(CXX) -c $(INCPATH) $(CXXFLAGS) -o main.o main.cpp

mainwindow.o: mainwindow.cpp mainwindow.h \
		qcustomplot.h \
		ui_mainwindow.h
	$(CXX) -c $(INCPATH) $(CXXFLAGS) -o mainwindow.o mainwindow.cpp

qcustomplot.o: qcustomplot.cpp qcustomplot.h
	$(CXX) -c $(INCPATH) $(CXXFLAGS) -o qcustomplot.o qcustomplot.cpp

moc_mainwindow.o: moc_mainwindow.cpp 
	$(CXX) -c $(INCPATH) $(CXXFLAGS) -o moc_mainwindow.o moc_mainwindow.cpp

moc_qcustomplot.o: moc_qcustomplot.cpp 
	$(CXX) -c $(INCPATH) $(CXXFLAGS) -o moc_qcustomplot.o moc_qcustomplot.cpp

####### Install

install_target: first FORCE
	@$(CHK_DIR_EXISTS) $(INSTALL_ROOT)/home/felix/ || $(MKDIR) $(INSTALL_ROOT)/home/felix/ 
	-$(INSTALL_PROGRAM) "$(QMAKE_TARGET)" "$(INSTALL_ROOT)/home/felix/$(QMAKE_TARGET)"
	-$(STRIP) "$(INSTALL_ROOT)/home/felix/$(QMAKE_TARGET)"

uninstall_target:  FORCE
	-$(DEL_FILE) "$(INSTALL_ROOT)/home/felix/$(QMAKE_TARGET)"
	-$(DEL_DIR) $(INSTALL_ROOT)/home/felix/ 


install:  install_target  FORCE

uninstall: uninstall_target   FORCE

FORCE:

